import litellm 
from PIL import Image
from docpro.utils.image_utils import image_to_base64
from docpro.modules import BaseProcessorInterface


class GLMOCRVLLMConnector(BaseProcessorInterface):
    def __init__(self, 
                 url: str, 
                 model: str="hosted_vllm/glm-ocr",
                 api_key: str="your-api-key-here"):
        """
        Initializes the GLMOCRVLLMConnector.

        Args:
            url (str): The base URL for the vLLM API endpoint.
            model (str, optional): The name of the model to use. 
                Defaults to "hosted_vllm/glm-ocr".
            api_key (str, optional): api key for model.
                Defaults to "your-api-key-here".
        """

        self.url = url
        self.model = model 
        self._key = api_key


    def _get_message(self, 
                     b64_image: str, 
                     task: str|None=None):
        """
        Constructs the message payload for the vision-language model.

        Args:
            b64_image (str): The base64 encoded string of the image.
            task (str | None, optional): The specific task instruction for the model. 
                Defaults to "Text Recognition:".

        Returns:
            dict: A dictionary representing the user message containing the image 
            data URL and the text prompt.
        """

        task = task if task else "Text Recognition:"
        messages = {
                    "role": "user",
                    "content": [
                        {"type": "image_url", "image_url": {"url": f"data:image/png;base64,{b64_image}"}},
                        {"type": "text", "text": f"{task}"},
                    ]
                }
        return messages


    def process(self, 
                image: Image.Image, 
                task: str|None=None):
        """
        Processes an image to extract text or structured data using a vision-language model.

        Converts the input image to a base64 string, constructs the API message, 
        and sends a completion request to the specified vLLM endpoint.

        Args:
            image (PIL.Image.Image): The input image to be processed.
            task (str | None, optional): The specific task instruction for the model. 
                Defaults to "Text Recognition:".

        Returns:
            str: The text content generated by the model in response to the prompt.
        """
        
        b64_image = image_to_base64(image)
        messages = [self._get_message(b64_image, task)]

        response = litellm.completion(
            model=self.model, 
            messages=messages,
            api_base=self.url,
            temperature=0.0,
            api_key=self._key) 
        
        response = response.to_dict()
        content = response["choices"][0]["message"]["content"]

        return content